/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dev.ansida.chat.client;

import dev.ansida.chat.backend.ChatController;
import dev.ansida.chat.common.Group;
import java.util.List;

/**
 *
 * @author PC
 */
public class ChatMulticastMain extends javax.swing.JFrame {

    // Khai báo các thuộc tính mạng Multicast ở đầu class
    private ChatController controller;
    private static final String MULTICAST_IP = "224.1.1.1";
    private static final int PORT = 5007;
    private java.net.MulticastSocket socket;
    private java.net.InetAddress group;
    private java.net.InetSocketAddress groupAddress;

    public ChatMulticastMain() {
        initComponents();
        startAppBackend();
    }
    // Đặt hàm này vào trong Constructor của JFrame, ngay DƯỚI dòng initComponents();

    // Khai báo trong lớp JFrame chính
// Viết trong hàm khởi tạo JFrame, ngay dưới lệnh initComponents();
    private void startAppBackend() {
        // Khởi tạo bộ điều khiển trên cổng 5007 và tên mặc định
        controller = new ChatController(5007, "User_" + (int) (Math.random() * 100));

        // ĐĂNG KÝ NHẬN SỰ KIỆN TỪ BACKEND ĐỂ VẼ LÊN SẦN FRONT-END ĐÃ KÉO THẢ
        controller.setChatUpdateListener(new ChatController.ChatUpdateListener() {
            @Override
            public void onGroupListLoaded(List<Group> groups) {
                // Nạp danh sách đối tượng Group vào GroupSelectionPanel của bạn
                for (Group g : groups) {
                    groupSelectionPanel1.addGroup(g);
                }
            }

            @Override
            public void onChatHistoryUpdated(List<Message> currentMessages) {
                // Đẩy luồng vẽ lại giao diện an toàn trong Swing
                javax.swing.SwingUtilities.invokeLater(() -> {
                    chatArea.setText(""); // Xóa khung hiển thị cũ
                    for (Message m : currentMessages) {
                        chatArea.append(String.format("[%s] %s: %s\n",
                                m.getFormattedTime(), m.getSender(), m.getContent()));
                    }
                    chatArea.setCaretPosition(chatArea.getDocument().getLength()); // Cuộn xuống cuối
                });
            }

            @Override
            public void onError(String errorMessage) {
                javax.swing.JOptionPane.showMessageDialog(MainFrame.this, errorMessage);
            }
        });

        // Chạy kiến trúc điều khiển
        controller.start();

        // Liên kết sự kiện khi click từ GroupSelectionPanel sang Controller
        groupSelectionPanel1.setGroupSelectionListener(selectedGroup -> {
            controller.handleSwitchGroup(selectedGroup);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChatMulticastMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChatMulticastMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChatMulticastMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChatMulticastMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChatMulticastMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
